const mongoose = require('mongoose');

const PerformanceMetricSchema = new mongoose.Schema({
    student: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    attendancePercentage: { type: Number, default: 0 },
    avgAssignmentMarks: { type: Number, default: 0 },
    participationScore: { type: Number, default: 0 }, // Based on notes uploaded/forum activity
    rank: { type: Number, default: 0 },
    history: [{
        date: { type: Date, default: Date.now },
        score: Number
    }],
    aiInsights: { type: String } // Text generated by Groq analysis
}, { timestamps: true });

module.exports = mongoose.model('PerformanceMetric', PerformanceMetricSchema);
